spring:
  datasource:
    url: jdbc:postgresql://supportdb-container:5432/supportdb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: 4lTE23/TMFOP/OoS4g8YQrbhTgu6Yv5PkxYgz8ZNA/4=
    expiration: 86400000